version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/ToDoListApi/ToDoListApi.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/ToDoListApi/ToDoListApi.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      steps: 
        - checkout
        - run: 
            name: Restore packages 
            command: 
              dotnet restore
        - run:
            name: Build App 
            command: 
              dotnet build
        
workflows:
  test_and_build:
    jobs:
      - build